/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectjava;
import clases.Conexion;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import projectjava.Login;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomi Altero
 */
public class info_usuario extends javax.swing.JFrame {
    String user = "" , user_update = "";
    int ID;


    public info_usuario() {
        initComponents();
        String user = Login.user;
        user_update = Usuarios_registrado.user_update; 
        setTitle("Informacion del usuario" + user_update + "SESION DE: " + user);
        
        jLabel1.setText("Informacion del usuario" +" "+ user_update);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("select * from usuarios where Username = '" + user_update + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()) {
                ID = rs.getInt("ID");
                txt_nombre.setText(rs.getString("Nombre"));
                txt_mail.setText(rs.getString("Mail"));
                txt_telefono.setText(rs.getString("Telefono"));
                txt_username.setText(rs.getString("Username"));
                txt_regBy.setText(rs.getString("Registrado_por"));
                
                txt_regBy.setEditable(false);
                
                
                comboBoxPermisos.setSelectedItem(rs.getString("tipo_nivel"));
                comboBoxEstatus.setSelectedItem(rs.getString("Estatus"));
                
            
            }
            cn.close();
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxPermisos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBoxEstatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_regBy = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFORMACION DEL USUARIO");
        jLabel1.setToolTipText("");

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 754, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 59, -1));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 76, 190, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, 59, -1));

        txt_mail.setBackground(new java.awt.Color(255, 255, 255));
        txt_mail.setForeground(new java.awt.Color(0, 0, 0));
        txt_mail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 116, 190, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, 59, -1));

        txt_telefono.setBackground(new java.awt.Color(255, 255, 255));
        txt_telefono.setForeground(new java.awt.Color(0, 0, 0));
        txt_telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 156, 190, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Permisos de:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, 70, -1));

        comboBoxPermisos.setBackground(new java.awt.Color(0, 0, 255));
        comboBoxPermisos.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxPermisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(comboBoxPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 196, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre de Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 79, 108, -1));

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setForeground(new java.awt.Color(0, 0, 0));
        txt_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 76, 190, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estatus:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 119, 59, -1));

        comboBoxEstatus.setBackground(new java.awt.Color(0, 0, 255));
        comboBoxEstatus.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(comboBoxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 116, 190, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Registrado por:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 159, 96, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Modificar Usuario");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 742, 38));

        txt_regBy.setBackground(new java.awt.Color(255, 255, 255));
        txt_regBy.setForeground(new java.awt.Color(0, 0, 0));
        txt_regBy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_regBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 156, 190, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Modificar Contraseña");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 298, 748, 38));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 800, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int permisos_cmb, estatus_cmb, validacion = 0;
        String nombre, mail, telefono, username, pass, permisos_string = "", estatus_string = "";
        
        mail = txt_mail.getText().trim();
        username = txt_username.getText().trim();
        nombre = txt_nombre.getText().trim();
        telefono = txt_telefono.getText().trim();
        permisos_cmb = comboBoxPermisos.getSelectedIndex() + 1;
        estatus_cmb = comboBoxEstatus.getSelectedIndex() + 1;
        
        if(mail.equals("")){
            validacion++;
        }
        if(username.equals("")){
            
            validacion++;
        }
        if(nombre.equals("")){
            
            validacion++;
        }
        if(telefono.equals("")){
            
            validacion++;
        }
        
        if (validacion == 0) {
            
            if(permisos_cmb == 1){
                permisos_string = "Administrador";
            } else if(permisos_cmb == 2){
                permisos_string = "Capturista";
            } else if(permisos_cmb == 3){
                permisos_string = "Desarrollador";
            }
            
            if(estatus_cmb == 1){
                estatus_string = "Activo";
            } else if(estatus_cmb == 2){
                estatus_string = "Inactivo";
            }
            
            try {
                
                Connection cn = Conexion.conectar();
                java.sql.PreparedStatement pst = cn.prepareStatement(
                "select Username from usuarios where Username = '" + username + "' and not ID = '" + ID + "'");
                
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    
                    
                    JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                    cn.close();
                    
                } else {
                    
                    Connection cn2 = Conexion.conectar();
                    java.sql.PreparedStatement pst2 = cn2.prepareStatement(
                    "update usuarios set Nombre=?, Mail=?, Telefono=?, Username=?, tipo_nivel=?, Estatus=? "
                            + "where ID = '" + ID + "'");
                    
                    pst2.setString(1, nombre);
                    pst2.setString(2, mail);
                    pst2.setString(3, telefono);
                    pst2.setString(4, username);
                    pst2.setString(5, permisos_string);
                    pst2.setString(6, estatus_string);
                    
                    pst2.executeUpdate();
                    cn2.close();
                    
                    JOptionPane.showMessageDialog(null, "Modificación correcta.");
                    
                }
                
            } catch (SQLException e) {
                System.err.println("Erorr al Actualizar." + e);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modif_pass vent4 = new modif_pass();
        vent4.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxEstatus;
    private javax.swing.JComboBox<String> comboBoxPermisos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_regBy;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
